[[rulesets]]
[rulesets.rules]
"{construction_menu}" = "{construction_menu}"
"{creatures}" = "{creatures}"
"{items}" = "{items}"
"{materials}" = "{materials}"
"{plants}" = "{plants}"
"{positions}" = "{positions}"
"{professions}" = "{professions}"
"{skills}" = "{skills}"
"{tasks}" = "{tasks}"
"{tiles}" = "{tiles}"
"{day}" = "{day}"
"{menu}" = "{menu}"
"{workshop}" = "{workshop}"
"{require}" = "{require}"
"{health}" = "{health}"
"{worldgen}" = "{worldgen}"
"{psychology}" = "{psychology}"
"{name}" = "{name}"
"{adv}" = "{adv}"
"{english_name}" = "{english_name}"
